<a href="https://colab.research.google.com/github/alexiaboboc/PMP_BobocAlexia_3A3/blob/main/Lab03/Tema.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ex. 1.**




>**$=>$ "Dacă"**
\
Dacă  $A \perp C \mid B$, atunci există două funcții pozitive $\phi_{A,B}(x_A, x_B)$, $\phi_{B,C}(x_B, x_C)$ și o constantă de normalizare $k>0$ astfel încât:
\
$P(A = x_A, B = x_B, C = x_C) = \frac{1}{k} \cdot \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C)$


\
$A \perp C \mid B$, înseamnă că A și C sunt independente condiționat de B, deci:
\
$P(A = x_A, C = x_C \mid B = x_B) = P(A = x_A \mid B = x_B) \cdot P(C = x_C \mid B = x_B)$
\
\
Folosind regula produsului pentru probabilitățile condiționate, putem rescrie astfel:
\
$P(A = x_A, C = x_C, B = x_B) = P(A = x_A \mid B = x_B) \cdot P(C = x_C \mid B = x_B) \cdot P(B = x_B)$
\
\
Observăm că putem să ne referim la  $\phi_{A,B}(x_A, x_B) = P(A = x_A \mid B = x_B) \cdot P(B = x_B)$  și  $\phi_{B,C}(x_B, x_C) = P(C = x_C \mid B = x_B)$, ambele funcții fiind pozitive, deoarece probabilitățile condiționate sunt pozitive.
\
\
Rezultă că  $P(A = x_A, B = x_B, C = x_C)$ poate fi factorizat sub forma:
\
$P(A = x_A, B = x_B, C = x_C) = \frac{1}{k} \cdot \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C)$, unde $k>0$ este o constantă de normalizare.

\


> **$<=$ "Numai dacă"**
 Dacă $ P(A = x_A, B = x_B, C = x_C) = \frac{1}{k} \cdot \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C)$,
atunci $ A \perp C \mid B $

\
Calculăm probabilitatea condiționată $P(A = x_A, C = x_C \mid B = x_B)$, folosind regula probabilității condiționate:
\
$P(A = x_A, C = x_C \mid B = x_B) = \frac{P(A = x_A, B = x_B, C = x_C)}{P(B = x_B)}$
\
\
Folosim factorizarea:
\
$P(A = x_A, C = x_C \mid B = x_B) = \frac{\frac{1}{k} \cdot \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C)}{P(B = x_B)}
$
\
\
Rescriem ca:
\
$P(A = x_A, C = x_C \mid B = x_B) = \frac{\phi_{A,B}(x_A, x_B)}{P(B = x_B)} \cdot \frac{\phi_{B,C}(x_B, x_C)}{P(B = x_B)}$, deoarece factorul $\frac{1}{k}$ este un factor de normalizare care asigură că probabilitățile se însumează la 1 și putem să-l reducem când lucrăm cu distribuții condiționate, deoarece normalizarea distribuțiilor este implicită.
\
\
Putem interpreta ca:
- $\phi_{A,B}(x_A, x_B)$  reprezintă funcția de potențial care descrie interacțiunea dintre  A  și  B
- $\phi_{A,B}(x_A, x_B)$  reprezintă funcția de potențial care descrie interacțiunea dintre  A  și  B
- $P(B = x_B)$  este un factor de normalizare care face ca probabilitatea să fie corectă, asigurând că probabilitățile condiționate  $P(A, C \mid B)$  însumează la 1 pentru fiecare valoare a lui  B

Această formă sugerează că fiecare termen din produs depinde de  $B = x_B$ , iar potențialele  $\phi_{A,B}$  și  $\phi_{B,C}$  pot fi interpretate ca probabilități condiționate ale fiecărei variabile date  B.

\
$P(A = x_A \mid B = x_B)$  poate fi exprimată astfel:


$P(A = x_A \mid B = x_B) = \frac{\phi_{A,B}(x_A, x_B)}{P(B = x_B)}$

\
$P(C = x_C \mid B = x_B)$  poate fi exprimată astfel:

$P(C = x_C \mid B = x_B) = \frac{\phi_{B,C}(x_B, x_C)}{P(B = x_B)}$
\
\
Rezultă că putem rescrie expresia astfel:
$
P(A = x_A, C = x_C \mid B = x_B) = P(A = x_A \mid B = x_B) \cdot P(C = x_C \mid B = x_B)
$,
care este definiția $ A \perp C \mid B$.
\
\
\
Ambele sensuri au fost demonstrate **=>** echivalență demonstrată.




**Ex. 2.**

In [3]:
pip install pgmpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 18.2 MB/s eta 0:00:00


In [6]:
from pgmpy.models import MarkovModel
from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import BeliefPropagation

# date de intrare
n = int(input("numarul de statii meteo: "))  # numarul de statii
edges = []  #muchii dintre statiile meteo
print("vecinii fiecarei statii sub forma: 1 2 (pentru muchie intre S1 si S2)")
for _ in range(n - 1):  # graf aciclic => n-1 muchii
    edge = tuple(map(int, input("Muchie: ").split()))
    edges.append(edge)

# probabilitatile initiale pentru fiecare statie (Soare, Ploaie, Nori)
prob_initiale = []
for i in range(n):
    p_s = float(input(f"P(S) pentru S{i+1}: "))
    p_p = float(input(f"P(P) pentru S{i+1}: "))
    p_n = float(input(f"P(N) pentru S{i+1}: "))
    prob_initiale.append((p_s, p_p, p_n))

# matricea potentialului intre statiile vecine
potentials_matrix = [
    [0.7, 0.2, 0.1],
    [0.2, 0.6, 0.2],
    [0.1, 0.3, 0.6]
]

# crearea modelului Markovian
model = MarkovModel()

# adaugarea nodurilor (statiile meteo)
model.add_nodes_from([i for i in range(n)])

# adaugarea muchiilor (dependentele dintre statiile meteo)
model.add_edges_from(edges)

# definirea potentialelor pentru fiecare muchie (pereche de statii vecine)
factors = []

for edge in edges:
    factor = DiscreteFactor(
        variables=edge,                 # perechea de variabile (statiile vecine)
        cardinality=[3, 3],             # fiecare statie poate fi intr-una din cele 3 stari
        values=potentials_matrix        # matricea potentialelor pentru fiecare pereche
    )
    model.add_factors(factor)

# adaugarea probabilitatilor initiale pentru fiecare statie
for i in range(n):
    factor = DiscreteFactor(
        variables=[i],                  # fiecare statie individual
        cardinality=[3],                # 3 stări pentru fiecare stație
        values=prob_initiale[i]         # probabilitatile initiale pentru Soare, Ploaie, Nori
    )
    model.add_factors(factor)

# verificarea daca modelul este corect si echilibrat
assert model.check_model()

# realizarea inferentei folosind obiect de tip BeliefPropagation
bp_infer = BeliefPropagation(model)

# estimarea MAP (Maximum A Posteriori) pentru fiecare statie => starea cea mai probabila pt fiecare statie
map_result = bp_infer.map_query(variables=[i for i in range(n)]) #traduce

# rezultat
state_map = {0: 'Soare', 1: 'Ploaie', 2: 'Nori'} #traduce rezultatul obtinut de la map_query in stari
for i in range(n):
    print(f"Statia S{i+1}: {state_map[map_result[i]]}")

Introduceți numărul de stații meteo: 5
Introduceți vecinii fiecărei stații sub forma: S1 S2 (pentru o muchie între stațiile S1 și S2)
Muchie: 0 1
Muchie: 1 2
Muchie: 2 3
Muchie: 3 4
Introduceți P(S) pentru stația S1: 0.6
Introduceți P(P) pentru stația S1: 0.3
Introduceți P(N) pentru stația S1: .1
Introduceți P(S) pentru stația S2: 0.4
Introduceți P(P) pentru stația S2: 0.2
Introduceți P(N) pentru stația S2: 0.4
Introduceți P(S) pentru stația S3: 0.5
Introduceți P(P) pentru stația S3: 0.3
Introduceți P(N) pentru stația S3: 0.2
Introduceți P(S) pentru stația S4: 0.2
Introduceți P(P) pentru stația S4: 0.5
Introduceți P(N) pentru stația S4: 0.3
Introduceți P(S) pentru stația S5: 0.4
Introduceți P(P) pentru stația S5: 0.3
Introduceți P(N) pentru stația S5: 0.2


Stația S1: Soare
Stația S2: Soare
Stația S3: Soare
Stația S4: Soare
Stația S5: Soare


**Ex. 3.**

In [1]:
pip install pgmpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 10.7 MB/s eta 0:00:00


In [ ]:
import numpy as np
import random
import matplotlib.pyplot as plt
from pgmpy.models import MarkovModel
from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import BeliefPropagation

# a) generare imagine de dimensiune 5x5
original_image = np.random.randint(0, 256, (5, 5))  # img 5x5 (pixeli intre 0 si 255)
print("Imaginea:")
print(original_image)

# b) adaugare zgomot la imagine
noisy_image = original_image.copy()
num_noisy_pixels = int(0.1 * original_image.size)  # 10% dintre pixeli
noisy_indices = random.sample(range(original_image.size), num_noisy_pixels)

for idx in noisy_indices:
    row, col = divmod(idx, 5)
    noisy_image[row, col] = random.randint(0, 255)  # zgomot aleatoriu

print("imaginea cu zgomot:")
print(noisy_image)

# c) definire Markoviene (MRF) pe un grid 2D
model = MarkovModel()

# adaugarea nodurilor (un nod pentru fiecare pixel din imagine)
for i in range(5):
    for j in range(5):
        model.add_node((i, j))

# adaugarea muchiilor intre pixeli vecini (Nord, Sud, Est, Vest)
for i in range(5):
    for j in range(5):
        if i > 0:  # vecin la nord
            model.add_edge((i, j), (i - 1, j))
        if i < 4:  # vecin la sud
            model.add_edge((i, j), (i + 1, j))
        if j > 0:  # vecin la vest
            model.add_edge((i, j), (i, j - 1))
        if j < 4:  # vecin la est
            model.add_edge((i, j), (i, j + 1))

# definirea parametrilor
lambda_reg = 0.5  # factor de regularizare

# c) definirea potentialelor pentru functia de energie
factors = []

# functia de energie:
# prima componenta: penalizarea diferentei dintre pixelul curat si pixelul observat
# a doua componenta: penalizarea diferentelor intre pixeli vecini (N, S, E, W)

# potentiale pentru fiecare pixel observat
for i in range(5):
    for j in range(5):
        y_ij = noisy_image[i, j]  # pixelul observat cu zgomot
        potential_values = np.array([np.exp(-lambda_reg * (x_ij - y_ij) ** 2) for x_ij in range(256)]) #lista valori potential pt functia de energie
        # pt fiecare pixel
        factor = DiscreteFactor(
            variables=[(i, j)], #pixelul
            cardinality=[256], #0-255 =>256 valori
            values=potential_values
        )
        model.add_factors(factor)

# definirea potentialelor pentru pixelii vecini
for i in range(5):
    for j in range(5):
        if i > 0:  # vecin nord
            potential_values = np.exp(-np.square(np.arange(256).reshape(256, 1) - np.arange(256).reshape(1, 256)))
            factor = DiscreteFactor(
                variables=[(i, j), (i - 1, j)], #pixel curent
                cardinality=[256, 256], #ambii pixeli iau val de la 0 la 255
                values=potential_values
            )
            model.add_factors(factor)

        if j > 0:  # vecin vest
            potential_values = np.exp(-np.square(np.arange(256).reshape(256, 1) - np.arange(256).reshape(1, 256)))
            factor = DiscreteFactor(
                variables=[(i, j), (i, j - 1)],
                cardinality=[256, 256],
                values=potential_values
            )
            model.add_factors(factor)

# verificarea modelului
assert model.check_model()

# d) inferenta MAP pentru denoising-ul imaginii folosind Belief Propagation
bp_infer = BeliefPropagation(model)
map_result = bp_infer.map_query(variables=[(i, j) for i in range(5) for j in range(5)])

# reconstruirea imaginii estimate
denoised_image = np.zeros((5, 5), dtype=int)
for i in range(5):
    for j in range(5):
        denoised_image[i, j] = map_result[(i, j)]

print("Imaginea denoisata:")
print(denoised_image)

# afisarea imaginilor originala, zgomotată și denoisată
plt.figure(figsize=(10, 4))
plt.subplot(1, 3, 1)
plt.title("Imaginea Originala")
plt.imshow(original_image, cmap='gray', vmin=0, vmax=255)

plt.subplot(1, 3, 2)
plt.title("Imaginea cu Zgomot")
plt.imshow(noisy_image, cmap='gray', vmin=0, vmax=255)

plt.subplot(1, 3, 3)
plt.title("Imaginea Denoisata")
plt.imshow(denoised_image, cmap='gray', vmin=0, vmax=255)

plt.show()

Imaginea:
[[ 86 225 171  10 255]
 [152  25 136 159 202]
 [146 236 115  35  71]
 [137 231 117 174  24]
 [166  47 170 132 224]]
imaginea cu zgomot:
[[ 86 225 171  10 255]
 [152  25 136 159 202]
 [146 236 115  35  71]
 [137  79 117 174  24]
 [ 11  47 170 132 224]]
